

# run_all:main.c
# 	gcc -o m main.c `pkg-config --cflags gtk+-3.0` `pkg-config --libs gtk+-3.0`

#  libgtk-3-0:amd64  libgtk2.0-0:amd64 

run_all:browser.c
	gcc -o b browser.c `pkg-config --cflags gtk+-3.0` `pkg-config --libs gtk+-3.0` 
	# `pkg-config --libs webkitgtk-1.0`
